# Generated by Django 3.2.10 on 2021-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.CharField(
                choices=[('Abstract', 'Abstract'), ('Aerial', 'Aerial'), ('Architectural', 'Architectural'),
                         ('Black And White', 'Black White'), ('Conceptual', 'Conceptual'), ('Fashion', 'Fashion'),
                         ('Food', 'Food'), ('HDR', 'Hdr'), ('Landscape', 'Landscape'), ('Mobile', 'Mobile'),
                         ('Macro', 'Macro'), ('Nature', 'Nature'), ('Night', 'Night'), ('Portrait', 'Portrait'),
                         ('Sports', 'Sports'), ('Street', 'Street'), ('Sunrise', 'Sunrise'), ('Sunset', 'Sunset'),
                         ('Tilt Shift', 'Tilt Shift'), ('Travel', 'Travel'), ('Underwater', 'Underwater'),
                         ('Urban', 'Urban'), ('uncategorized', 'Uncategorized'), ('Wedding', 'Wedding'),
                         ('Wildlife', 'Wildlife')], default='uncategorized', max_length=256),
        ),
    ]
